src/BankCloud/BankCloud.Web/Controllers/OrdersController.cs
using System.Linq;
using AutoMapper;
using BankCloud.Data.Entities;
using BankCloud.Data.Entities.Enums;
using BankCloud.Models.BindingModels.Orders;
using BankCloud.Services.Common;
using BankCloud.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BankCloud.Web.Controllers
{
    public class OrdersController : Controller
    {
        
        private readonly IMapper mapper;
        private readonly IProductsService productsService;
        private readonly IUsersService usersService;
        private readonly IAccountsService accountsService;
        private readonly IOrdersService ordersService;

        public OrdersController(IProductsService productsService, IUsersService usersService,
            IMapper mapper, IAccountsService accountsService, IOrdersService ordersService)
        {
            
            this.productsService = productsService;
            this.usersService = usersService;
            this.mapper = mapper;
            this.accountsService = accountsService;
            this.ordersService = ordersService;
        }

        [Authorize]
        [HttpGet("/Orders/OrderLoan/{id}")]
        public IActionResult OrderLoan(string id)
        {
            Product loanFromDb = this.productsService.GetProductById(id);

            BankUser userFromDb = this.usersService.GetCurrentUser();

            if (!userFromDb.Accounts.Any())
            {
                return this.Redirect("/Accounts/Activate");
            }

            this.ViewData["Accounts"] = this.accountsService.GetUserAccounts();

            var view = this.mapper.Map<OrdersOrderLoanInputModel>(loanFromDb);

            view.UserCurrencyTypes = this.accountsService.GetUserAccounts()
                .Select(x => x.Currency.Name).ToList();

            view.MonthlyFee = BankCloudCalculator.CalculateMounthlyFee(loanFromDb);

            return View(view);
        }

        [Authorize]
        [AutoValidateAntiforgeryToken]
        [HttpPost]
        public IActionResult OrderLoan(OrdersOrderLoanInputModel model)
        {
            Product loanFromDb = this.productsService.GetProductById(model.Id);

            BankUser userFromDb = this.usersService.GetCurrentUser();

            this.ViewData["Accounts"] = this.accountsService.GetUserAccounts();
            
            OrderLoan order = this.mapper.Map<OrderLoan>(model);

            if (userFromDb.Id == loanFromDb.Account.BankUserId)
            {
                return this.Redirect("/");
            }

            if (!userFromDb.Accounts.Any())
            {
                return this.Redirect("/Accounts/Activate");
            }
            //TODO: add message for invalid parameters
            if (!ModelState.IsValid || model.Amount > loanFromDb.Amount
                || model.Period > loanFromDb.Period
                || model.InterestRate != loanFromDb.InterestRate)
            {
                //TODO: refactor this!!!
                model.Name = loanFromDb.Name;
                model.CurrencyName = loanFromDb.Account.Currency.Name;
                model.UserCurrencyTypes = this.accountsService.GetUserAccounts()
                .Select(x => x.Currency.Name).ToList();
                return this.View(model);
            }

            this.ordersService.AddOrderLoan(order, loanFromDb);

            return this.Redirect("/Users/OrderedLoans");
        }

        [Authorize]
        [HttpGet("/Orders/OrderSave/{id}")]
        public IActionResult OrderSave(string id)
        {
            Product saveFromDb = this.productsService.GetProductById(id);

            BankUser userFromDb = this.usersService.GetCurrentUser();

            if (!userFromDb.Accounts.Any())
            {
                return this.Redirect("/Accounts/Activate");
            }

            this.ViewData["Accounts"] = this.accountsService.GetUserAccounts();

            var view = this.mapper.Map<OrdersOrderSaveInputModel>(saveFromDb);

            view.UserCurrencyTypes = this.accountsService.GetUserAccounts()
                .Select(x => x.Currency.Name).ToList();

            return this.View(view);
        }

        [Authorize]
        [AutoValidateAntiforgeryToken]
        [HttpPost]
        public IActionResult OrderSave(OrdersOrderSaveInputModel model)
        {
            Product saveFromDb = this.productsService.GetProductById(model.Id);

            BankUser userFromDb = this.usersService.GetCurrentUser();

            if (userFromDb.Id == saveFromDb.Account.BankUserId)
            {
                return this.Redirect("/");
            }

            if (!userFromDb.Accounts.Any())
            {
                return this.Redirect("/Accounts/Activate");
            }

            this.ViewData["Accounts"] = this.accountsService.GetUserAccounts();

            OrderSave order = this.mapper.Map<OrderSave>(model);

            if (!ModelState.IsValid 
                || saveFromDb.InterestRate != model.InterestRate 
                || saveFromDb.Period != model.Period)
            {
                return this.View(model);
            }

            this.ordersService.AddOrderSave(order, saveFromDb);

            return this.Redirect("/Users/OrderedSaves");
        }
    }
}

src/BankCloud/BankCloud.Web/Controllers/ProductsController.cs
using System.Collections.Generic;
using AutoMapper;
using BankCloud.Models.ViewModels;
using BankCloud.Models.ViewModels.Products;
using BankCloud.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BankCloud.Web.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IMapper mapper;
        private readonly IProductsService productsService;

        public ProductsController(IProductsService productsService, IMapper mapper)
        {
            this.productsService = productsService;
            this.mapper = mapper;
        }
        
        public IActionResult Loans()
        {
            var loansFromDb = this.productsService.GetAllActiveLoans();

            var view = mapper.Map<List<ProductsLoansViewModel>>(loansFromDb);

            return View(view);
        }

        [HttpGet("/Products/LoanDetails/{id}")]
        public IActionResult LoanDetails(string id)
        {
            var loanFromDb = this.productsService.GetProductById(id);

            var view = mapper.Map<ProductsLoanDetailsViewModel>(loanFromDb);

            return this.View(view);
        }

        public IActionResult Saves()
        {
            var savesFromDb = this.productsService.GetAllActiveSaves();

            var view = mapper.Map<List<ProductsSavesViewModel>>(savesFromDb);

            return View(view);
        }

        [HttpGet("/Products/SaveDetails/{id}")]
        public IActionResult SaveDetails(string id)
        {
            var saveFromDb = this.productsService.GetProductById(id);

            var view = mapper.Map<ProductsSaveDetailsViewModel>(saveFromDb);

            return this.View(view);
        }

        //TODO add other products!!!
    }
}

src/BankCloud/BankCloud.Web/Views/Products/LoanAll.cshtml
@model IEnumerable<BankCloud.Models.ViewModels.LoanAllViewModel>

@{
    ViewData["Title"] = "LoanAll";
}

<br />

<section class="section-agents section-t8">

    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-8">
                <div class="title-single-box">
                    <h1 class="title-single">Our Amazing Loans</h1>
                    <span class="color-text-a">Grid Categories</span>
                </div>
            </div>
            <div class="col-md-12 col-lg-4">
                <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="#">Home</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                            Categories Grid
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</section>
<!--/ Property Grid Star /-->
<section class="property-grid grid">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="grid-option">
                    <form>
                        <select class="custom-select">
                            <option selected>All</option>
                            <option value="1">New to Old</option>
                            <option value="2">Old  to New</option>
                        </select>
                    </form>
                </div>
            </div>
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="card-box-a card-shadow">
                        <div class="img-box-a">
                            <img src="~/img/loan-2.jpg" alt="" class="img-a img-fluid">
                        </div>
                        <div class="card-overlay">
                            <div class="card-overlay-a-content">
                                <div class="card-header-a">
                                    <h2 class="card-title-a">
                                        <a href="#">
                                            Loans
                                            <br /> @item.Name
                                        </a>
                                    </h2>
                                </div>
                                <div class="card-body-a">
                                    <div class="price-box d-flex">
                                        <a href="/Products/LoanDetails/@item.Id"><span class="price-a">Buy now</span></a>
                                    </div>
                                    @*<a href="property-single.html" class="link-a">
                                            Click here to view
                                            <span class="ion-ios-arrow-forward"></span>
                                        </a>*@
                                </div>
                                <div class="card-footer-a">
                                    <ul class="card-info d-flex justify-content-around">
                                        <li>
                                            <h4 class="card-info-title">Up to</h4>
                                            <span>
                                                @item.Amount
                                            </span>
                                        </li>
                                        <li>
                                            <h4 class="card-info-title">Curency</h4>
                                            <span>
                                                @item.Curency
                                            </span>
                                        </li>
                                        <li>
                                            <h4 class="card-info-title">Rate</h4>
                                            <span>
                                                @item.InterestRate %
                                            </span>
                                        </li>
                                        <li>
                                            <h4 class="card-info-title">Period to</h4>
                                            <span>
                                                @item.Period months
                                            </span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }

            @*<table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Id)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new {  id=item.Name}) |
                                @Html.ActionLink("LoanOrder", "Orders", new { id = item.Id },null)
                                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>*@
        </div>
    </div>
</section>

src/BankCloud/BankCloud.Web/Views/Products/LoanDetails.cshtml
@model BankCloud.Models.ViewModels.Products.ProductsLoanDetailsViewModel

@{
    ViewData["Title"] = "LoanDetails";
}

<section class="intro-single">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-8">
                <div class="title-single-box">
                    <h1 class="title-single">@Model.Name</h1>
                    <span class="color-text-a">@Model.Seller</span>
                </div>
            </div>
            <div class="col-md-12 col-lg-4">
                <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="/">Home</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="/Products/Loans">Loans</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                            @Model.Name
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</section>


<section class="property-single nav-arrow-b">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="row justify-content-between">
                    <div class="col-md-5 col-lg-4">
                        <div class="property-price d-flex justify-content-center foo">
                            <div class="card-header-c d-flex">
                                <div class="card-box-ico">
                                    <span class="ion-money">@Model.CurrencyIso</span>
                                </div>
                                <div class="card-title-c align-self-center">
                                    <h5 class="title-c">@Model.Amount</h5>
                                </div>
                            </div>
                        </div>
                        <div class="property-summary">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="title-box-d section-t4">
                                        <h3 class="title-d">Quick Summary</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="summary-list">
                                <ul class="list">
                                    <li class="d-flex justify-content-between">
                                        <strong>Product Name:</strong>
                                        <span>@Model.Name</span>
                                    </li>
                                    <li class="d-flex justify-content-between">
                                        <strong>Seller:</strong>
                                        <span>@Model.Seller</span>
                                    </li>
                                    <li class="d-flex justify-content-between">
                                        <strong>Interest Rate:</strong>
                                        <span>@Model.InterestRate%</span>
                                    </li>
                                    <li class="d-flex justify-content-between">
                                        <strong>Amount up to:</strong>
                                        <span>@Model.Amount @Model.CurrencyIso</span>
                                    </li>
                                    <li class="d-flex justify-content-between">
                                        <strong>Period up to:</strong>
                                        <span>@Model.Period months</span>
                                    </li>
                                    <li class="d-flex justify-content-between">
                                        <strong>Charge Absorption:</strong>
                                        <span>@Model.Commission %</span>
                                    </li>
                                    <li class="d-flex justify-content-between">
                                        <strong>Curency:</strong>
                                        <span>@Model.CurrencyName</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-7 col-lg-7 section-md-t3">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="title-box-d">
                                    <h3 class="title-d">Description</h3>
                                </div>
                            </div>
                        </div>
                        <div class="property-description">
                            <p class="description color-text-a">
                                @Model.Description
                            </p>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="title-box-d">
                                    <h3 class="title-d">Get it now</h3>
                                </div>
                            </div>
                        </div>
                        <div class="amenities-list color-text-a text-center">
                            <div class="mx-auto">
                                @if (User.Identity.Name == @Model.Seller)
                                {
                                    <a href="/Products/Loans" class="btn btn-a">Back</a>
                                    <a href="/Users/ProductLoans" class="btn btn-a">MyCloud</a>
                                }
                                else
                                {
                                    <a href="/Orders/OrderLoan/@Model.Id" class="btn btn-a">Order</a>
                                    <a href="/Products/Loans" class="btn btn-a">Back</a>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

src/BankCloud/BankCloud.Web/Views/Products/Loans.cshtml
@model IEnumerable<BankCloud.Models.ViewModels.Products.ProductsLoansViewModel>

@{
    ViewData["Title"] = "Loans";
}

<section class="section-agents section-t8">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-8">
                <div class="title-single-box">
                    <h1 class="title-single">Our Amazing Loans</h1>
                    <span class="color-text-a">Grid Loans</span>
                </div>
            </div>
            <div class="col-md-12 col-lg-4">
                <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="/">Home</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                            Loans Grid
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</section>

<section class="property-grid grid">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="grid-option">
                    @*<form>
                        <select class="custom-select">
                            <option selected>All</option>
                            <option value="1">New to Old</option>
                            <option value="2">Old  to New</option>
                        </select>
                    </form>*@
                </div>
            </div>
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="card-box-a card-shadow">
                        <div class="img-box-a">
                            <img src="@item.AdUrl" alt="" class="img-a img-fluid">
                        </div>
                        <div class="card-overlay">
                            <div class="card-overlay-a-content">
                                <div class="card-header-a">
                                    <h2 class="card-title-a">
                                        <a href="/Products/LoanDetails/@item.Id">
                                            Loan
                                            <br /> @item.Name
                                        </a>
                                    </h2>
                                </div>
                                <div class="card-body-a">
                                    <div class="price-box d-flex">
                                        <a href="/Products/LoanDetails/@item.Id"><span class="price-a">Buy now</span></a>
                                    </div>
                                </div>
                                <div class="card-footer-a">
                                    <ul class="card-info d-flex justify-content-around">
                                        <li>
                                            <h4 class="card-info-title">Up to</h4>
                                            <span>
                                                @item.Amount.ToString("F0")
                                            </span>
                                        </li>
                                        <li>
                                            <h4 class="card-info-title">Curency</h4>
                                            <span>
                                                @item.Currency
                                            </span>
                                        </li>
                                        <li>
                                            <h4 class="card-info-title">Rate</h4>
                                            <span>
                                                @item.InterestRate %
                                            </span>
                                        </li>
                                        <li>
                                            <h4 class="card-info-title">Period to</h4>
                                            <span>
                                                @item.Period months
                                            </span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

src/BankCloud/BankCloud.Web/Views/Products/SaveDetails.cshtml
@model BankCloud.Models.ViewModels.Products.ProductsSaveDetailsViewModel
@{
    ViewData["Title"] = "SaveDetails";
}

<section class="intro-single">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-8">
                <div class="title-single-box">
                    <h1 class="title-single">@Model.Name</h1>
                    <span class="color-text-a">@Model.Seller</span>
                </div>
            </div>
            <div class="col-md-12 col-lg-4">
                <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="/">Home</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="/Products/Saves">Saves</a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                            @Model.Name
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</section>


<section class="property-single nav-arrow-b">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="row justify-content-between">
                    <div class="col-md-5 col-lg-4">
                        <div class="property-price d-flex justify-content-center foo">
                            <div class="card-header-c d-flex">
                                <div class="card-box-ico">
                                    <span class="ion-money">@Model.CurrencyIso</span>
                                </div>
                                <div class="card-title-c align-self-center">
                                    <h5 class="title-c">@Model.InterestRate %</h5>
                                </div>
                            </div>
                        </div>
                        <div class="property-summary">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="title-box-d section-t4">
                                        <h3 class="title-d">Quick Summary</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="summary-list">
                                <ul class="list">
                                    <li class="d-flex justify-content-between">
                                        <strong>Product Name:</strong>
                                        <span>@Model.Name</span>
                                    </li>
                                    <li class="d-flex justify-content-between">
                                        <strong>Seller:</strong>
                                        <span>@Model.Seller</span>
                                    </li>
                                    <li class="d-flex justify-content-between">
                                        <strong>Interest Rate:</strong>
                                        <span>@Model.InterestRate%</span>
                                    </li>
                                    <li class="d-flex justify-content-between">
                                        <strong>For Period:</strong>
                                        @if (Model.Period == 0)
                                        {
                                            <span>Open</span>
                                        }
                                        else
                                        {
                                            <span>
                                                @Model.Period months
                                            </span>
                                        }
                                    </li>
                                    <li class="d-flex justify-content-between">
                                        <strong>Penalty Interest:</strong>
                                        <span>@Model.PenaltyInterest %</span>
                                    </li>
                                    <li class="d-flex justify-content-between">
                                        <strong>Curency:</strong>
                                        <span>@Model.CurrencyName</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-7 col-lg-7 section-md-t3">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="title-box-d">
                                    <h3 class="title-d">Description</h3>
                                </div>
                            </div>
                        </div>
                        <div class="property-description">
                            <p class="description color-text-a">
                                @Model.Description
                            </p>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="title-box-d">
                                    <h3 class="title-d">Get it now</h3>
                                </div>
                            </div>
                        </div>
                        <div class="amenities-list color-text-a text-center">
                            <div class="mx-auto">
                                @if (User.Identity.Name == @Model.Seller)
                                {
                                    <a href="/Products/Saves" class="btn btn-a">Back</a>
                                    <a href="/Users/ProductSaves" class="btn btn-a">MyCloud</a>
                                }
                                else
                                {
                                    <a href="/Orders/OrderSave/@Model.Id" class="btn btn-a">Order</a>
                                    <a href="/Products/Saves" class="btn btn-a">Back</a>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>